version: "3.5"

services:
  db:
    container_name: wisestudy_mysql_local
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wisestudy
      MYSQL_USER: wisestudy
      MYSQL_PASSWORD: wise$$tudy
      TZ: Asia/Seoul

  adminer:
    container_name: wisestudy_mysql_adminer
    image: adminer
    restart: always
    ports:
      - 8088:8080
