FROM centos:centos7
LABEL name="wisestudy dev environment" \
      build-date=$(BUILD_DATE)

# 사용자 지정, 초기 비밀번호 설정
USER root
RUN echo "root:wisestudy" | chpasswd

# 환경 설정
SHELL ["/bin/bash", "-c"]

# Timezone 설정
ENV TIMEZONE Asia/Seoul
ENV SRC_DIR /home/src
RUN ln -snf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && echo ${TIMEZONE} > /etc/timezone

# Default directory 생성
RUN mkdir -p /home/apps \
 && mkdir -p ${SRC_DIR} \
 && mkdir -p /home/temp \
 && chown nobody:nobody /home/temp

# DRPM epel 저장소 설치
RUN yum provides '*/applydeltarpm' \
 && yum install -y --quiet --setopt=tsflags=nodocs deltarpm epel-release \
 && yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm \
 && yum update -y --quiet --setopt=tsflags=nodocs \
 && yum groupinstall -y development \
 && yum clean all

# Install SSH, cronie, vim
RUN yum install -y --quiet --setopt=tsflags=nodocs cronie wget curl
RUN yum install -y --quiet --setopt=tsflags=nodocs openssh-server openssh-clients openssh-askpass
RUN ssh-keygen -A
RUN yum install -y --quiet --setopt=tsflags=nodocs vim
RUN echo -e "\nalias vi='vim'" >> /etc/bashrc
RUN echo -e "\nset ts=4\nset hlsearch\nset sw=4\nset showmatch\nset encoding=utf-8\nset fileencodings=utf-8,cp949" >> /etc/vimrc
RUN yum install -y --quiet --setopt=tsflags=nodocs gcc make gcc-c++ libxslt-devel

# Upgrade version of python 2 > 3
RUN yum install -y --quiet --setopt=tsflags=nodocs https://repo.ius.io/ius-release-el7.rpm
RUN yum install -y --quiet --setopt=tsflags=nodocs python36u python36u-devel python36u-libs python36u-pip
RUN cd ${SRC_DIR} \
 && wget https://bootstrap.pypa.io/get-pip.py --no-check-certificate \
 && python3.6 get-pip.py \
 && echo -e "\nalias python='\/usr\/bin\/python3'" >> /etc/bashrc

# Install Nginx with compile
## Install pcre 8.36
RUN cd ${SRC_DIR} \
 && wget https://ftp.pcre.org/pub/pcre/pcre-8.44.tar.gz \
 && tar -zxf pcre-8.44.tar.gz
RUN cd ${SRC_DIR}/pcre-8.44 \
 && ./configure --prefix=/usr/local \
 && make && make install
## Install zlib 1.2.8
RUN cd ${SRC_DIR} \
 && wget http://www.zlib.net/zlib-1.2.11.tar.gz \
 && tar -zxf zlib-1.2.11.tar.gz
RUN cd ${SRC_DIR}/zlib-1.2.11 \
 && ./configure --prefix=/usr/local \
 && make && make install
## Install nginx
RUN cd ${SRC_DIR} \
 && wget http://nginx.org/download/nginx-1.17.10.tar.gz \
 && tar -zxf nginx-1.17.10.tar.gz
RUN cd ${SRC_DIR}/nginx-1.17.10 \
 && ./configure --prefix=/home/apps/nginx1_17 --with-openssl=/usr/bin \
 && make && make install

# Install MySQL
RUN cd ${SRC_DIR} \
 && wget https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm \
 && rpm -Uvh mysql80-community-release-el7-3.noarch.rpm \
 && yum-config-manager --disable mysql80-community \
 && yum-config-manager --enable mysql57-community
RUN yum install -y --quiet --setopt=tsflags=nodocs mysql-community-server
